services:
  influxdb:
    image: influxdb:1.8
    environment:
      - TZ=Europe/Rome
      - INFLUXDB_DB=${INFLUXDB_DATABASE}
      - INFLUXDB_ADMIN_ENABLED=true
      - INFLUXDB_ADMIN_USER=${INFLUXDB_ADMIN_USER}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_ADMIN_PASSWORD}
      - INFLUXDB_USER=${INFLUXDB_USER}
      - INFLUXDB_USER_PASSWORD=${INFLUXDB_PASSWORD}
    ports:
      - "8086:8086"
    networks:
      - siotd
    volumes:
      - influxdb:/var/lib/influxdb
    restart: always

  grafana:
    image: grafana/grafana:8.4.6-ubuntu
    ports:
      - "3000:3000"
    networks:
      - siotd
    volumes:
      - grafana:/var/lib/grafana
    depends_on:
      - influxdb
    restart: always

networks:
  siotd:

volumes:
  influxdb:
  grafana: